export const locations = [
  {
    id: "palm-beach",
    name: "Palm Beach",
    description: "Luxury home automation solutions for Palm Beach's prestigious waterfront properties and estates.",
    image: "/palm-beach-florida.png",
    zipCodes: ["33480", "33481", "33482"],
    features: ["Waterfront Properties", "Historic Estates", "Luxury Condominiums"],
  },
  {
    id: "palm-beach-gardens",
    name: "Palm Beach Gardens",
    description: "Smart home technology for Palm Beach Gardens' modern communities and golf course properties.",
    image: "/palm-beach-gardens-florida.png",
    zipCodes: ["33403", "33408", "33410", "33418"],
    features: ["Golf Course Communities", "Modern Homes", "Family Neighborhoods"],
  },
  {
    id: "jupiter",
    name: "Jupiter",
    description: "Advanced home automation for Jupiter's coastal homes and inland communities.",
    image: "/jupiter-florida-coastal-homes.png",
    zipCodes: ["33458", "33469", "33477", "33478"],
    features: ["Coastal Properties", "Inland Communities", "New Construction"],
  },
  {
    id: "tequesta",
    name: "Tequesta",
    description: "Custom home technology solutions for Tequesta's exclusive residential communities.",
    image: "/placeholder.svg?height=800&width=1200&query=Tequesta Florida luxury homes",
    zipCodes: ["33469", "33477"],
    features: ["Exclusive Communities", "Waterfront Homes", "Custom Estates"],
  },
  {
    id: "west-palm-beach",
    name: "West Palm Beach",
    description: "Comprehensive home automation for West Palm Beach's diverse residential and commercial properties.",
    image: "/placeholder.svg?height=800&width=1200&query=West Palm Beach Florida downtown",
    zipCodes: [
      "33401",
      "33402",
      "33403",
      "33404",
      "33405",
      "33406",
      "33407",
      "33409",
      "33411",
      "33412",
      "33413",
      "33414",
      "33415",
      "33417",
    ],
    features: ["Downtown Living", "Suburban Homes", "Commercial Properties"],
  },
  {
    id: "stuart",
    name: "Stuart",
    description: "Smart home solutions for Stuart's waterfront properties and historic neighborhoods.",
    image: "/placeholder.svg?height=800&width=1200&query=Stuart Florida waterfront homes",
    zipCodes: ["34994", "34995", "34996", "34997"],
    features: ["Historic Downtown", "Waterfront Properties", "Boating Communities"],
  },
  {
    id: "hobe-sound",
    name: "Hobe Sound",
    description: "Luxury home automation for Hobe Sound's exclusive beachfront and golf communities.",
    image: "/placeholder.svg?height=800&width=1200&query=Hobe Sound Florida beachfront homes",
    zipCodes: ["33455", "33475"],
    features: ["Beachfront Properties", "Golf Communities", "Nature Preserves"],
  },
  {
    id: "north-palm-beach",
    name: "North Palm Beach",
    description: "Premium home technology for North Palm Beach's waterfront condos and single-family homes.",
    image: "/placeholder.svg?height=800&width=1200&query=North Palm Beach Florida condominiums",
    zipCodes: ["33403", "33408"],
    features: ["Waterfront Condos", "Single Family Homes", "Marina Communities"],
  },
  {
    id: "boca-raton",
    name: "Boca Raton",
    description: "Sophisticated home automation for Boca Raton's luxury communities and high-rise residences.",
    image: "/placeholder.svg?height=800&width=1200&query=Boca Raton Florida luxury communities",
    zipCodes: [
      "33427",
      "33428",
      "33429",
      "33431",
      "33432",
      "33433",
      "33434",
      "33486",
      "33487",
      "33488",
      "33496",
      "33497",
      "33498",
      "33499",
    ],
    features: ["Luxury Communities", "High-Rise Living", "Golf Course Estates"],
  },
  {
    id: "delray-beach",
    name: "Delray Beach",
    description: "Modern home technology solutions for Delray Beach's vibrant downtown and beachside properties.",
    image: "/placeholder.svg?height=800&width=1200&query=Delray Beach Florida downtown",
    zipCodes: ["33444", "33445", "33446", "33447", "33448", "33482", "33483", "33484"],
    features: ["Downtown Living", "Beachside Properties", "Arts District"],
  },
]

export function getLocationById(id: string) {
  return locations.find((location) => location.id === id)
}

export function getAllLocations() {
  return locations
}
